export const SettingsCss = Object.freeze({
    BODY: "settings-body",
    COURSE_CHECKBOX: "settings-course-checkbox",
    COURSE_DOT: "settings-course-dot",
    COURSE_NAME: "settings-course-name",
    COURSES_LIST: "settings-courses-list",
    COURSES_LIST_ID: "spark-settings-courses-list",
    COURSES_SECTION_ID: "spark-settings-courses",
    COURSE_ROW: "settings-course-row",
    DAYS_BACK_INPUT_ID: "spark-setting-days-back",
    DESCRIPTION: "settings-description",
    INPUT: "settings-input",
    LABEL: "settings-label",
    PANEL_HEADER: "settings-header",
    PANEL_ID: "spark-settings-panel",
    PANEL_TITLE: "settings-title",
    SECTION: "settings-section",
});
