export const SettingsCss = Object.freeze({
    BODY: "settings-body",
    COURSE_CHECKBOX: "settings-course-checkbox",
    COURSE_DOT: "settings-course-dot",
    COURSE_NAME: "settings-course-name",
    COURSES_LIST: "settings-courses-list",
    COURSES_LIST_ID: "spark-settings-courses-list",
    COURSES_SECTION_ID: "spark-settings-courses",
    COURSE_ROW: "settings-course-row",
    DAYS_BACK_INPUT_ID: "spark-setting-days-back",
    DESCRIPTION: "settings-description",
    INPUT: "settings-input",
    LABEL: "settings-label",
    OPEN: "spark-settings-open",
    PANEL_HEADER: "settings-header",
    PANEL_ID: "spark-settings-panel",
    PANEL_TITLE: "settings-title",
    SECTION: "settings-section",
});

export const PanelCss = Object.freeze({
    WIDGET_ID: "spark-widget",
    PANEL_ID: "spark-panel",
    RESIZE_HANDLE: "spark-resize-handle",
    CALENDAR_CONTAINER_ID: "calendar-container",
    TOGGLE_BTN_ID: "spark-toggle-btn",
    TOGGLE_BTN_TITLE: "Toggle Spark panel",
    WIDGET_HIDDEN: "hidden",
});

export const FrequencyChartCss = Object.freeze({
    CONTAINER: "frequency-chart-container",
    CONTAINER_ID: "frequency-chart",
    NAV_BTN: "frequency-chart-btn",
    PREV_BTN_ID: "frequency-chart-prev",
    NEXT_BTN_ID: "frequency-chart-next",
    GRID: "frequency-chart-grid",
    HEADER_ROW: "frequency-chart-header-row",
    WEEK_LABEL: "frequency-chart-week-label",
    SETTINGS_BTN: "spark-settings-btn",
    REFRESH_BTN: "spark-refresh-btn",
    SPINNING: "spinning",
    BTN_SPACER: "spark-btn-spacer",
    FAQ_BTN: "faq-btn",
    CHART_ROW: "frequency-chart-row",
    LAST_FETCHED: "frequency-chart-last-fetched",
    DAY: "frequency-day",
    DAY_TODAY: "frequency-day--today",
    DAY_LABEL: "frequency-day-label",
    DAY_DATE: "frequency-day-date",
    BAR_CONTAINER: "frequency-bar-container",
    BAR: "frequency-bar",
    DAY_COUNT: "frequency-day-count",
});

export const CalendarCss = Object.freeze({
    DATE_HEADER: "calendar-date-header",
    DATE_TITLE: "date-title",
    ITEMS_CONTAINER: "calendar-items-container",
});
